// common js --> every file is a module (by default)
// modules --> encapsukated code (only share minimum)
const name = require('./3-name')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
require(`./7-mind-grenade`)
console.log(data)
sayHi(name.sharmeen)
sayHi(name.shumaim)